CREATE TABLE `applications` (
	`id` text PRIMARY KEY NOT NULL,
	`business_name` text NOT NULL,
	`business_type` text NOT NULL,
	`years_operating` text NOT NULL,
	`current_website_url` text,
	`instagram_handle` text,
	`facebook_handle` text,
	`activity_level` text,
	`google_profile_url` text,
	`google_review_count` integer,
	`services_description` text NOT NULL,
	`biggest_challenge` text NOT NULL,
	`content_readiness` text NOT NULL,
	`credentials` text,
	`contact_name` text NOT NULL,
	`contact_email` text NOT NULL,
	`contact_phone` text NOT NULL,
	`consent_terms` integer NOT NULL,
	`consent_feedback` integer NOT NULL,
	`status` text DEFAULT 'new' NOT NULL,
	`internal_score` integer,
	`internal_notes` text,
	`reviewer` text,
	`created_at` text DEFAULT (datetime('now')) NOT NULL
);
